project_id = "zqscoubnjzyjmgefneoe"

[functions.mpesa-stk-push]
verify_jwt = false

[functions.mpesa-callback]
verify_jwt = false

[functions.telegram-bot]
verify_jwt = false

[functions.paystack-initialize]
verify_jwt = false

[functions.paystack-verify]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false
